# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources.ui'
#
# Created: Thu May 08 16:06:31 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmPrincipal(object):
    def setupUi(self, frmPrincipal):
        frmPrincipal.setObjectName(_fromUtf8("frmPrincipal"))
        frmPrincipal.resize(955, 609)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPrincipal.sizePolicy().hasHeightForWidth())
        frmPrincipal.setSizePolicy(sizePolicy)
        frmPrincipal.setWindowTitle(_fromUtf8("Frame"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/video-projector.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmPrincipal.setWindowIcon(icon)
        frmPrincipal.setFrameShape(QtGui.QFrame.StyledPanel)
        frmPrincipal.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(frmPrincipal)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dockProjectionsTools = QtGui.QDockWidget(frmPrincipal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockProjectionsTools.sizePolicy().hasHeightForWidth())
        self.dockProjectionsTools.setSizePolicy(sizePolicy)
        self.dockProjectionsTools.setMinimumSize(QtCore.QSize(740, 80))
        self.dockProjectionsTools.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockProjectionsTools.setAutoFillBackground(False)
        self.dockProjectionsTools.setFloating(False)
        self.dockProjectionsTools.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockProjectionsTools.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockProjectionsTools.setObjectName(_fromUtf8("dockProjectionsTools"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rbBible = QtGui.QRadioButton(self.dockWidgetContents)
        self.rbBible.setChecked(True)
        self.rbBible.setObjectName(_fromUtf8("rbBible"))
        self.horizontalLayout_4.addWidget(self.rbBible)
        self.rbSong = QtGui.QRadioButton(self.dockWidgetContents)
        self.rbSong.setObjectName(_fromUtf8("rbSong"))
        self.horizontalLayout_4.addWidget(self.rbSong)
        self.txtSearch = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtSearch.setMinimumSize(QtCore.QSize(0, 30))
        self.txtSearch.setStyleSheet(_fromUtf8(""))
        self.txtSearch.setInputMask(_fromUtf8(""))
        self.txtSearch.setText(_fromUtf8(""))
        self.txtSearch.setEchoMode(QtGui.QLineEdit.Normal)
        self.txtSearch.setObjectName(_fromUtf8("txtSearch"))
        self.horizontalLayout_4.addWidget(self.txtSearch)
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.cmdGotoLive = QtGui.QPushButton(self.dockWidgetContents)
        self.cmdGotoLive.setEnabled(False)
        self.cmdGotoLive.setCheckable(False)
        self.cmdGotoLive.setChecked(False)
        self.cmdGotoLive.setAutoRepeat(False)
        self.cmdGotoLive.setAutoExclusive(False)
        self.cmdGotoLive.setAutoRepeatDelay(1)
        self.cmdGotoLive.setAutoRepeatInterval(1)
        self.cmdGotoLive.setFlat(False)
        self.cmdGotoLive.setObjectName(_fromUtf8("cmdGotoLive"))
        self.horizontalLayout_4.addWidget(self.cmdGotoLive)
        self.cmdDirectToLive = QtGui.QPushButton(self.dockWidgetContents)
        self.cmdDirectToLive.setEnabled(False)
        self.cmdDirectToLive.setCheckable(True)
        self.cmdDirectToLive.setObjectName(_fromUtf8("cmdDirectToLive"))
        self.horizontalLayout_4.addWidget(self.cmdDirectToLive)
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_4.addWidget(self.line_2)
        self.cmdColorScreen = QtGui.QPushButton(self.dockWidgetContents)
        self.cmdColorScreen.setEnabled(False)
        self.cmdColorScreen.setObjectName(_fromUtf8("cmdColorScreen"))
        self.horizontalLayout_4.addWidget(self.cmdColorScreen)
        self.cmdMainView = QtGui.QPushButton(self.dockWidgetContents)
        self.cmdMainView.setEnabled(False)
        self.cmdMainView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.cmdMainView.setObjectName(_fromUtf8("cmdMainView"))
        self.horizontalLayout_4.addWidget(self.cmdMainView)
        self.line_3 = QtGui.QFrame(self.dockWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_4.addWidget(self.line_3)
        self.cmdLive = QtGui.QPushButton(self.dockWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/Live.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cmdLive.setIcon(icon1)
        self.cmdLive.setIconSize(QtCore.QSize(28, 28))
        self.cmdLive.setCheckable(True)
        self.cmdLive.setAutoRepeat(False)
        self.cmdLive.setObjectName(_fromUtf8("cmdLive"))
        self.horizontalLayout_4.addWidget(self.cmdLive)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.dockProjectionsTools.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.dockProjectionsTools)
        self.scrollArea = QtGui.QScrollArea(frmPrincipal)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 927, 444))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.txtPreview = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPreview.sizePolicy().hasHeightForWidth())
        self.txtPreview.setSizePolicy(sizePolicy)
        self.txtPreview.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtPreview.setFont(font)
        self.txtPreview.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtPreview.setUndoRedoEnabled(False)
        self.txtPreview.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.txtPreview.setReadOnly(True)
        self.txtPreview.setObjectName(_fromUtf8("txtPreview"))
        self.dockProjectionsControls = QtGui.QDockWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockProjectionsControls.sizePolicy().hasHeightForWidth())
        self.dockProjectionsControls.setSizePolicy(sizePolicy)
        self.dockProjectionsControls.setMinimumSize(QtCore.QSize(0, 398))
        self.dockProjectionsControls.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dockProjectionsControls.setAcceptDrops(True)
        self.dockProjectionsControls.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockProjectionsControls.setAutoFillBackground(False)
        self.dockProjectionsControls.setFloating(False)
        self.dockProjectionsControls.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockProjectionsControls.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockProjectionsControls.setObjectName(_fromUtf8("dockProjectionsControls"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkSearchForward = QtGui.QCheckBox(self.dockWidgetContents_3)
        self.chkSearchForward.setChecked(True)
        self.chkSearchForward.setObjectName(_fromUtf8("chkSearchForward"))
        self.gridLayout.addWidget(self.chkSearchForward, 8, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 12, 0, 1, 1)
        self.cmdFullScreen = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdFullScreen.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/Fullscreen-64.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cmdFullScreen.setIcon(icon2)
        self.cmdFullScreen.setCheckable(True)
        self.cmdFullScreen.setObjectName(_fromUtf8("cmdFullScreen"))
        self.gridLayout.addWidget(self.cmdFullScreen, 4, 0, 1, 2)
        self.cmdCompactView = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdCompactView.setEnabled(False)
        self.cmdCompactView.setCheckable(True)
        self.cmdCompactView.setObjectName(_fromUtf8("cmdCompactView"))
        self.gridLayout.addWidget(self.cmdCompactView, 14, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cmdPrevious = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdPrevious.setEnabled(False)
        self.cmdPrevious.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmdPrevious.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/Go back.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cmdPrevious.setIcon(icon3)
        self.cmdPrevious.setIconSize(QtCore.QSize(20, 20))
        self.cmdPrevious.setCheckable(False)
        self.cmdPrevious.setChecked(False)
        self.cmdPrevious.setObjectName(_fromUtf8("cmdPrevious"))
        self.horizontalLayout_3.addWidget(self.cmdPrevious)
        self.cmdNext = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdNext.setEnabled(False)
        self.cmdNext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmdNext.setAutoFillBackground(False)
        self.cmdNext.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/Go forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cmdNext.setIcon(icon4)
        self.cmdNext.setIconSize(QtCore.QSize(20, 20))
        self.cmdNext.setObjectName(_fromUtf8("cmdNext"))
        self.horizontalLayout_3.addWidget(self.cmdNext)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cmdAddSong = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdAddSong.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/add-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdAddSong.setIcon(icon5)
        self.cmdAddSong.setObjectName(_fromUtf8("cmdAddSong"))
        self.horizontalLayout_9.addWidget(self.cmdAddSong)
        self.cmdEditSong = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdEditSong.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/edit-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdEditSong.setIcon(icon6)
        self.cmdEditSong.setObjectName(_fromUtf8("cmdEditSong"))
        self.horizontalLayout_9.addWidget(self.cmdEditSong)
        self.cmdDeleteSong = QtGui.QPushButton(self.dockWidgetContents_3)
        self.cmdDeleteSong.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/delete-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdDeleteSong.setIcon(icon7)
        self.cmdDeleteSong.setObjectName(_fromUtf8("cmdDeleteSong"))
        self.horizontalLayout_9.addWidget(self.cmdDeleteSong)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 2)
        self.sLiveFont = QtGui.QSlider(self.dockWidgetContents_3)
        self.sLiveFont.setMinimum(1)
        self.sLiveFont.setMaximum(100)
        self.sLiveFont.setTracking(False)
        self.sLiveFont.setOrientation(QtCore.Qt.Horizontal)
        self.sLiveFont.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sLiveFont.setTickInterval(0)
        self.sLiveFont.setObjectName(_fromUtf8("sLiveFont"))
        self.gridLayout.addWidget(self.sLiveFont, 11, 1, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setIndent(5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 11, 0, 1, 1)
        self.saCmdSlides = QtGui.QScrollArea(self.dockWidgetContents_3)
        self.saCmdSlides.setWidgetResizable(True)
        self.saCmdSlides.setObjectName(_fromUtf8("saCmdSlides"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 453, 138))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmdSlides = QtGui.QGridLayout()
        self.cmdSlides.setObjectName(_fromUtf8("cmdSlides"))
        self.gridLayout_2.addLayout(self.cmdSlides, 0, 0, 1, 1)
        self.saCmdSlides.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.saCmdSlides, 7, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.cbLiveIn = QtGui.QComboBox(self.dockWidgetContents_3)
        self.cbLiveIn.setObjectName(_fromUtf8("cbLiveIn"))
        self.gridLayout.addWidget(self.cbLiveIn, 3, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cbImagesView = QtGui.QComboBox(self.dockWidgetContents_3)
        self.cbImagesView.setObjectName(_fromUtf8("cbImagesView"))
        self.horizontalLayout_7.addWidget(self.cbImagesView)
        self.cmdRefreshImageView = QtGui.QToolButton(self.dockWidgetContents_3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/refresh-20.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cmdRefreshImageView.setIcon(icon8)
        self.cmdRefreshImageView.setIconSize(QtCore.QSize(20, 20))
        self.cmdRefreshImageView.setObjectName(_fromUtf8("cmdRefreshImageView"))
        self.horizontalLayout_7.addWidget(self.cmdRefreshImageView)
        self.gridLayout.addLayout(self.horizontalLayout_7, 12, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.dockProjectionsControls.setWidget(self.dockWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.statusBar = QtGui.QWidget(frmPrincipal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 28))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.statusBar)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblStatusIcon = QtGui.QLabel(self.statusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatusIcon.sizePolicy().hasHeightForWidth())
        self.lblStatusIcon.setSizePolicy(sizePolicy)
        self.lblStatusIcon.setMinimumSize(QtCore.QSize(0, 25))
        self.lblStatusIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblStatusIcon.setText(_fromUtf8(""))
        self.lblStatusIcon.setPixmap(QtGui.QPixmap(_fromUtf8(":/main/icons/valid-24.png")))
        self.lblStatusIcon.setScaledContents(False)
        self.lblStatusIcon.setObjectName(_fromUtf8("lblStatusIcon"))
        self.horizontalLayout.addWidget(self.lblStatusIcon)
        self.lblGeneralStatus = QtGui.QLabel(self.statusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGeneralStatus.sizePolicy().hasHeightForWidth())
        self.lblGeneralStatus.setSizePolicy(sizePolicy)
        self.lblGeneralStatus.setText(_fromUtf8(""))
        self.lblGeneralStatus.setTextFormat(QtCore.Qt.LogText)
        self.lblGeneralStatus.setIndent(10)
        self.lblGeneralStatus.setObjectName(_fromUtf8("lblGeneralStatus"))
        self.horizontalLayout.addWidget(self.lblGeneralStatus)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblButton = QtGui.QLabel(self.statusBar)
        self.lblButton.setText(_fromUtf8(""))
        self.lblButton.setObjectName(_fromUtf8("lblButton"))
        self.horizontalLayout.addWidget(self.lblButton)
        self.line_5 = QtGui.QFrame(self.statusBar)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout.addWidget(self.line_5)
        self.lblFullScreen = QtGui.QLabel(self.statusBar)
        self.lblFullScreen.setEnabled(False)
        self.lblFullScreen.setObjectName(_fromUtf8("lblFullScreen"))
        self.horizontalLayout.addWidget(self.lblFullScreen)
        self.line_4 = QtGui.QFrame(self.statusBar)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.lblLive = QtGui.QLabel(self.statusBar)
        self.lblLive.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLive.setFont(font)
        self.lblLive.setObjectName(_fromUtf8("lblLive"))
        self.horizontalLayout.addWidget(self.lblLive)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.statusBar)

        self.retranslateUi(frmPrincipal)
        QtCore.QMetaObject.connectSlotsByName(frmPrincipal)
        frmPrincipal.setTabOrder(self.rbBible, self.rbSong)
        frmPrincipal.setTabOrder(self.rbSong, self.txtSearch)
        frmPrincipal.setTabOrder(self.txtSearch, self.cmdGotoLive)
        frmPrincipal.setTabOrder(self.cmdGotoLive, self.cmdDirectToLive)
        frmPrincipal.setTabOrder(self.cmdDirectToLive, self.cmdColorScreen)
        frmPrincipal.setTabOrder(self.cmdColorScreen, self.cmdMainView)
        frmPrincipal.setTabOrder(self.cmdMainView, self.cmdLive)
        frmPrincipal.setTabOrder(self.cmdLive, self.scrollArea)

    def retranslateUi(self, frmPrincipal):
        self.dockProjectionsTools.setWindowTitle(_translate("frmPrincipal", "Projection Tools", None))
        self.rbBible.setText(_translate("frmPrincipal", "Bible", None))
        self.rbBible.setShortcut(_translate("frmPrincipal", "Ctrl+B", None))
        self.rbSong.setText(_translate("frmPrincipal", "Song", None))
        self.rbSong.setShortcut(_translate("frmPrincipal", "Ctrl+S", None))
        self.txtSearch.setToolTip(_translate("frmPrincipal", "Search...", None))
        self.txtSearch.setPlaceholderText(_translate("frmPrincipal", "Search... (F3)", None))
        self.cmdGotoLive.setText(_translate("frmPrincipal", "Go to Live (F5)", None))
        self.cmdGotoLive.setShortcut(_translate("frmPrincipal", "F5", None))
        self.cmdDirectToLive.setText(_translate("frmPrincipal", "Direct To Live (F6)", None))
        self.cmdDirectToLive.setShortcut(_translate("frmPrincipal", "F6", None))
        self.cmdColorScreen.setText(_translate("frmPrincipal", "ColorScreen", None))
        self.cmdMainView.setText(_translate("frmPrincipal", "Image View (F10)", None))
        self.cmdMainView.setShortcut(_translate("frmPrincipal", "F10", None))
        self.cmdLive.setText(_translate("frmPrincipal", "Live (F12)", None))
        self.cmdLive.setShortcut(_translate("frmPrincipal", "F12", None))
        self.dockProjectionsControls.setWindowTitle(_translate("frmPrincipal", "Projections Controls", None))
        self.chkSearchForward.setText(_translate("frmPrincipal", "Bible Search Forward", None))
        self.label_2.setText(_translate("frmPrincipal", "Image View", None))
        self.cmdFullScreen.setText(_translate("frmPrincipal", "Fullscreen (F11)", None))
        self.cmdFullScreen.setShortcut(_translate("frmPrincipal", "F11", None))
        self.cmdCompactView.setText(_translate("frmPrincipal", "Compact View", None))
        self.cmdPrevious.setToolTip(_translate("frmPrincipal", "Go to previous slide", None))
        self.cmdPrevious.setShortcut(_translate("frmPrincipal", "Ctrl+Left", None))
        self.cmdNext.setToolTip(_translate("frmPrincipal", "Go to next slide", None))
        self.cmdNext.setShortcut(_translate("frmPrincipal", "Ctrl+Right", None))
        self.cmdAddSong.setText(_translate("frmPrincipal", "Add Song", None))
        self.cmdEditSong.setText(_translate("frmPrincipal", "Edit Song", None))
        self.cmdDeleteSong.setText(_translate("frmPrincipal", "Delete Song", None))
        self.label.setText(_translate("frmPrincipal", "Live Font", None))
        self.label_3.setText(_translate("frmPrincipal", "Live in", None))
        self.cmdRefreshImageView.setToolTip(_translate("frmPrincipal", "Refresh Images View List", None))
        self.cmdRefreshImageView.setText(_translate("frmPrincipal", "...", None))
        self.lblFullScreen.setText(_translate("frmPrincipal", "FullScreen", None))
        self.lblLive.setText(_translate("frmPrincipal", "LIVE", None))

import resources_rc
